{
 "title": "TradeTools - Base 2.0",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "indextypes",
    "query": "{\"find\": \"fields\", \"type\": \"text\"}"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "{\"find\": \"terms\", \"field\": \"domain.keyword\"}"
   },
   {
    "name": "service_name",
    "label": "Service  Name",
    "query": "{\"find\": \"terms\", \"field\": \"service_name.keyword\", \"query\": \"domain:$domain\"}"
   },
   {
    "name": "project_Key",
    "query": "{\"find\": \"terms\", \"field\": \"project_key.keyword\", \"query\": \"service_name:$service_name\"}"
   },
   {
    "name": "artifact",
    "label": "Artifact ID",
    "query": "{\"find\": \"terms\", \"field\": \"artifact.keyword\", \"query\": \"service_name:$service_name\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n  # **$project_Key**\n  \n\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "content": "<h3><u><center>Code Quality Stats</u></h3>"
  },
  {
   "title": "SonarQube",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "# of Issues" }
   ],
   "targets": [
    {
     "alias": "Bugs",
     "bucketAggs": [
      {
       "$$hashKey": "object:305",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:303",
       "field": "bugs",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Code Smells",
     "bucketAggs": [
      {
       "$$hashKey": "object:309",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:307",
       "field": "code_smell",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "vulnerablities",
     "bucketAggs": [
      {
       "$$hashKey": "object:313",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:311",
       "field": "vulnerabilities",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Debt",
     "bucketAggs": [
      {
       "$$hashKey": "object:317",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:315",
       "field": "SMELL_DEBT",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Duplicate Lines",
     "bucketAggs": [
      {
       "$$hashKey": "object:321",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:319",
       "field": "duplicated_lines_density",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Fortify",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "# of Issues" }
   ],
   "targets": [
    {
     "alias": "Low",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fortify_low",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Medium",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fortify_medium",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "High",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fortify_high",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Critial",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fortify_critical",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Total Issues",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "fortify_total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Cyclomatic Complexity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "complexity",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Current Code Coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "coverage",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Lines of Code",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ncloc",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name.keyword:$service_name AND artifact.keyword:$artifact",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "content": "<h3><u><center>Test Quality Stats</u></h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "content": "<h4><i>Environment - L1</i></h4>"
  },
  {
   "title": "L1 - Test Trends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_total",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L1 - Latest Test Stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L1 - Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_avg_response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name.keyword:$service_name AND artifact.keyword:$artifact.keyword",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "content": "<h4><i>Environment - L2</i></h4>"
  },
  {
   "title": "L2 - Test Trends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l1_test_total",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L2 - Latest Test Stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 40 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L2 - Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 40 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l2_avg_response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name:$service_name AND artifact:$artifact",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "content": "<h4><i>Environment - L3</i></h4>"
  },
  {
   "title": "L3 - Test Trends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_total",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L3 - Latest Test Stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L3 - Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l3_avg_response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name.keyword:$service_name AND artifact.keyword:$artifact",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 62 },
   "content": "<h4><i>Environment - L4</i></h4>"
  },
  {
   "title": "L4 - Test Trends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_total",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L4 - Latest Test Stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 64 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L4 - Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 64 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_avg_response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name.keyword:$service_name AND artifact.keyword:$artifact",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 },
   "content": "<h4><i>Environment - L6</i></h4>"
  },
  {
   "title": "L6 - Test Trends",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l6_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Total",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l4_test_total",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L6 - Latest Test Stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 76 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Pass",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l6_test_pass",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Fail",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l6_test_fail",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    },
    {
     "alias": "Not run",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l6_test_notrun",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "L6 - Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 76 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "l6_avg_response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "service_name.keyword:$service_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name.keyword:$service_name AND artifact.keyword:$artifact",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "content": "<h3><u><center>Build Information</u></h3>"
  },
  {
   "title": "Jenkins",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "service_name:$service_name AND artifact:$artifact",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}